# Generated by Django 5.1.3 on 2025-09-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('fechaCaducidad', models.CharField(max_length=5)),
                ('codigoAutorizacion', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComercio', models.CharField(max_length=16)),
                ('idTransaccion', models.CharField(max_length=16)),
                ('importe', models.FloatField()),
                ('marcaTiempo', models.DateTimeField(auto_now=True)),
                ('codigoRespuesta', models.CharField(default='000', max_length=3)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaApp.tarjeta')),
            ],
            options={
                'db_table': 'pago',
                'constraints': [models.UniqueConstraint(fields=('idTransaccion', 'idComercio'), name='unique_blocking_pago')],
            },
        ),
    ]
